// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GaryGravityResources
{
        public const string achievement_last_resort = "CgkI1OXD-eYaEAIQCw"; // <GPGSID>
        public const string achievement_born_ready = "CgkI1OXD-eYaEAIQFA"; // <GPGSID>
        public const string achievement_now_or_never = "CgkI1OXD-eYaEAIQCQ"; // <GPGSID>
        public const string achievement_blindsight = "CgkI1OXD-eYaEAIQDQ"; // <GPGSID>
        public const string achievement_topped_off = "CgkI1OXD-eYaEAIQDg"; // <GPGSID>
        public const string achievement_gold_digger = "CgkI1OXD-eYaEAIQEg"; // <GPGSID>
        public const string achievement_the_swift_and_the_furious = "CgkI1OXD-eYaEAIQAg"; // <GPGSID>
        public const string leaderboard_swifest_leaderboard = "CgkI1OXD-eYaEAIQBg"; // <GPGSID>
        public const string achievement_buff_em_up = "CgkI1OXD-eYaEAIQAQ"; // <GPGSID>
        public const string achievement_livin_la_vida_loca = "CgkI1OXD-eYaEAIQBQ"; // <GPGSID>
        public const string achievement_the_almighty_one = "CgkI1OXD-eYaEAIQEQ"; // <GPGSID>
        public const string achievement_breaking_bed = "CgkI1OXD-eYaEAIQBA"; // <GPGSID>
        public const string achievement_power_tripper = "CgkI1OXD-eYaEAIQEw"; // <GPGSID>
        public const string achievement_demolition_derby = "CgkI1OXD-eYaEAIQCg"; // <GPGSID>
        public const string achievement_on_a_roll = "CgkI1OXD-eYaEAIQDw"; // <GPGSID>
        public const string achievement_tv_or_not_tv = "CgkI1OXD-eYaEAIQEA"; // <GPGSID>
        public const string achievement_cant_stop_wont_stop = "CgkI1OXD-eYaEAIQAw"; // <GPGSID>

}

